FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-server ./apps/http-server

RUN bun install

ENV DATABASE_URL=${DATABASE_URL}
RUN bun run db:generate

EXPOSE 3002

CMD ["bun", "run", "start:backend"]